package:
  name: ne
  version: "3.0.1"

build:
  number: 2

source:
  fn: ne-3.0.1.tar.gz
  url: http://ne.di.unimi.it/ne-3.0.1.tar.gz
  patches:
    - ncurses.patch [not win]

requirements:
  build:
    - ncurses [not win]
  run:
    - ncurses [not win]

about:
  home: http://ne.di.unimi.it
  license: GPL3
  summary: ne is a free (GPL'd) text editor based on the POSIX standard that runs (we hope) on almost any UN*X machine.
