{% set version = "0.4.0" %}

package:
  name: python-fmask
  version: {{ version }}

build:
  number: 0

source:
  fn: python-fmask-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  md5: ddf8aa3245f8d891e67cab8abf21e288

requirements:
  build:
    - python
    - numpy
    - gdal
    - rios
  run:
    - python
    - numpy
    - gdal
    - rios
    
about:
  home: https://bitbucket.org/chchrsc/python-fmask
  license: GPLv3
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.
