{% set version = "0.4.2" %}

package:
  name: python-fmask
  version: {{ version }}

build:
  number: 0

source:
  fn: python-fmask-{{ version }}.tar.gz
  url: https://bitbucket.org/chchrsc/python-fmask/downloads/python-fmask-{{ version }}.tar.gz
  sha256: 2aba33c616920cec8dc6fd2fdac3aaab5a180a1e0ead892380c9b359e273cc02

requirements:
  build:
    - python
    - numpy x.x
    - gdal
    - rios
  run:
    - python
    - numpy x.x
    - gdal
    - rios
    
about:
  home: https://bitbucket.org/chchrsc/python-fmask
  license: GPLv3
  summary: Implementation in Python of the cloud and shadow algorithms known collectively as Fmask.
