package:
  name: envmaster
  version: "0.1.6"

source:
  hg_url: https://bitbucket.org/chchrsc/envmaster
  
requirements:
  build:
    - python
  run:
    - python
  
build:
  number: 0

about:
  home: https://bitbucket.org/chchrsc/envmaster
  license: GPLv2
  summary: Envmaster is a system for managing environment variables and paths in a clean and consistent manner. Similar to "modules", but using a python syntax instead of Tcl, and support for standard directory structures built in. 
