#!/bin/bash

cmake -D CMAKE_INSTALL_PREFIX=$PREFIX \
	-D SPDLIB_IO_INCLUDE_DIR=$PREFIX/include \
	-D SPDLIB_IO_LIB_PATH=$PREFIX/lib \
	-D HDF5_INCLUDE_DIR=$PREFIX/include \
	-D HDF5_LIB_PATH=$PREFIX/lib \
	-D GDAL_INCLUDE_DIR=$PREFIX/include \
	-D GDAL_LIB_PATH=$PREFIX/lib \
	-D CMAKE_BUILD_TYPE=Release \
	-D BOOST_INCLUDE_DIR=$PREFIX/include \
	-D BOOST_LIB_PATH=$PREFIX/lib \
	.

make -j$CPU_COUNT
make install


