package:
  name: pulsewaves
  version: 20170424

source:
  git_url: https://github.com/gillins/PulseWaves.git

build:
  number: 1
  skip: True  # [win and py36]
  features:
    - vc9     # [win and py27]
    - vc14    # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake
    - toolchain
    - msinttypes  # [win and py27]]
    - vc 9    # [win and py27]
    - vc 14   # [win and py35]
  run:
    - vc 9    # [win and py27]
    - vc 14   # [win and py35]

test:
  commands:
    - if not exist %LIBRARY_BIN%\\pulsewaves.dll exit 1   # [win]
    - if not exist %LIBRARY_LIB%\\pulsewaves.lib exit 1   # [win]
    - if not exist %LIBRARY_INC%\\pulsereader.hpp exit 1  # [win]
    - if not exist %LIBRARY_INC%\\pulsewriter.hpp exit 1  # [win]
    - test -f $PREFIX/lib/libpulsewaves.so                # [linux]
    - test -f $PREFIX/lib/libpulsewaves.dylib             # [osx]
    - test -f $PREFIX/include/pulsereader.hpp             # [unix]
    - test -f $PREFIX/include/pulsewriter.hpp             # [unix]

about:
  home: https://rapidlasso.com/pulsewaves/
  license: LGPL2.1
  license_file: COPYING.txt
  summary: An open source effort for a vendor-neutral exchange format for geo-referenced full waveform LiDAR

extra:
  recipe-maintainers:
    - gillins
    - danclewley
    - armstonj
