package:
  name: pynninterp
  version: 1.0

source:
  hg_url: https://bitbucket.org/petebunting/pynninterp

build:
  number: 4
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
  run:
    - python
    - numpy

test:
    imports:
        - pynninterp

about:
  home: https://bitbucket.org/petebunting/pynninterp
  license_file: LICENSE.txt
  summary: Natural Neighbour Interpolation for use with PyLidar.
