package:
  name: pynninterp
  version: 1.0

source:
  git_url: https://github.com/ubarsc/pynninterp

build:
  number: 8
  script: python setup.py install

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy 1.14
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
    imports:
        - pynninterp

about:
  home: https://bitbucket.org/petebunting/pynninterp
  license_file: LICENSE.txt
  summary: Natural Neighbour Interpolation for use with PyLidar.
