package:
  name: pynninterp
  version: 1.0

source:
  hg_url: https://bitbucket.org/petebunting/pynninterp

build:
  number: 6
  script: python setup.py install

requirements:
  build:
    - python
    - toolchain
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - msinttypes  # [win and py27]
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]

test:
    imports:
        - pynninterp

about:
  home: https://bitbucket.org/petebunting/pynninterp
  license_file: LICENSE.txt
  summary: Natural Neighbour Interpolation for use with PyLidar.
