package:
  name: pylidar
  version: 0.4.0

source:
  fn: pylidar-0.4.0.tar.gz
  url: https://bitbucket.org/chchrsc/pylidar/downloads/pylidar-0.4.0.tar.gz
  sha256: 6da5ed90e8947e60427de4e9008bf67625d2a055eeb760598665492f58cd41ae

requirements:
  build:
    - python
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - lastools
    - pulsewaves
    - zlib
    - gdal 2.1.*
    - toolchain
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - gdal 2.1.*
    - rios
    - numba
    - h5py
    - lastools
    - pulsewaves
    - zlib
    - pynninterp
    - statsmodels

build:
  number: 0
  script_env:
    - PYLIDAR_TESTDATA
    - LD_LIBRARY_PATH
  entry_points:
    - pylidar_index = pylidar.toolbox.cmdline.index:run
    - pylidar_translate = pylidar.toolbox.cmdline.translate:run
    - pylidar_info = pylidar.toolbox.cmdline.info:run
    - pylidar_tile = pylidar.toolbox.cmdline.tile:run
    - pylidar_rasterize = pylidar.toolbox.cmdline.rasterize:run
    - pylidar_test = pylidar.testing.testall:run
    - pylidar_canopy = pylidar.toolbox.cmdline.canopy:run

about:
  home: http://pylidar.org/
  license: GPLv3
  summary: Airborne and terrestrial lidar processing tools
