package:
  name: pylidar
  version: 0.2.1

source:
  hg_url: https://bitbucket.org/chchrsc/pylidar

requirements:
  build:
    - python
    - numpy
    - lastools
    - zlib
    - toolchain
  run:
    - python
    - numpy
    - gdal
    - rios
    - numba
    - h5py
    - lastools
    - zlib

build:
  number: 4
  entry_points:
    - pylidar_index = pylidar.toolbox.cmdline.index:run
    - pylidar_translate = pylidar.toolbox.cmdline.translate:run
    - pylidar_info = pylidar.toolbox.cmdline.info:run
    - pylidar_tile = pylidar.toolbox.cmdline.tile:run
    - pylidar_rasterize = pylidar.toolbox.cmdline.rasterize:run

about:
  home: http://pylidar.org/
  license: GPLv3
  summary: RIOS for LiDAR
