package:
  name: pylidar
  version: 0.1

source:
  hg_url: https://bitbucket.org/chchrsc/pylidar

requirements:
  build:
    - python
    - numpy
    - lastools
  run:
    - python
    - numpy
    - gdal
    - rios
    - numba
    - h5py
    - lastools [not win]

build:
  number: 1

about:
  home: http://pylidar.org/
  license: GPLv3
  summary: RIOS for LiDAR
