{% set version = "0.4.3" %}

package:
  name: pylidar
  version: {{ version }}

source:
  #url: https://github.com/ubarsc/pylidar/releases/download/pylidar-{{ version }}/pylidar-{{ version }}.tar.gz
  #sha256: 3d0d0fa3614082da7bb83e993d7ea9aa447e9d7dce0894eab804db233211e757
  git_url: https://github.com/ubarsc/pylidar.git
  git_tag: dev

build:
  number: 2
  skip: True  # [win and py27]
  script_env:
    - PYLIDAR_TESTDATA
    # LD_LIBRARY_PATH needed for Riegl driver
    - LD_LIBRARY_PATH  # [linux]
  entry_points:
    - pylidar_index = pylidar.toolbox.cmdline.index:run
    - pylidar_translate = pylidar.toolbox.cmdline.translate:run
    - pylidar_info = pylidar.toolbox.cmdline.info:run
    - pylidar_tile = pylidar.toolbox.cmdline.tile:run
    - pylidar_rasterize = pylidar.toolbox.cmdline.rasterize:run
    - pylidar_test = pylidar.testing.testall:run
    - pylidar_canopy = pylidar.toolbox.cmdline.canopy:run
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy 1.14
    - lastools 20171231
    - pulsewaves 20160127
    - zlib 1.2.*
    - gdal 3.0.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gdal 3.0.*
    - rios
    - numba
    - h5py
    - lastools 20171231
    - pulsewaves 20160127
    - zlib 1.2.*
    - pynninterp
    - statsmodels

about:
  home: http://pylidar.org/
  license: GPL3
  #license_file: LICENSE.txt
  summary: Airborne and terrestrial lidar processing tools
