package:
  name: pylidar
  version: 0.3.1

source:
  fn: pylidar-0.3.1.tar.gz
  url: https://bitbucket.org/chchrsc/pylidar/downloads/pylidar-0.3.1.tar.gz
  sha256: 03d57f437bd5a75f73b90b1da46ee10ff9fb61fa3e1bbb419caa829e754bbb77  

requirements:
  build:
    - python
    - numpy x.x
    - lastools
    - zlib
    - toolchain
  run:
    - python
    - numpy x.x
    - gdal
    - rios
    - numba
    - h5py
    - lastools
    - zlib
    - pynninterp
    - statsmodels

build:
  number: 1
  entry_points:
    - pylidar_index = pylidar.toolbox.cmdline.index:run
    - pylidar_translate = pylidar.toolbox.cmdline.translate:run
    - pylidar_info = pylidar.toolbox.cmdline.info:run
    - pylidar_tile = pylidar.toolbox.cmdline.tile:run
    - pylidar_rasterize = pylidar.toolbox.cmdline.rasterize:run
    - pylidar_test = pylidar.testing.testall:run
    - pylidar_canopy = pylidar.toolbox.cmdline.canopy:run

about:
  home: http://pylidar.org/
  license: GPLv3
  summary: Airborne and terrestrial lidar processing tools
