package:
  name: mapaccuracy
  version: 0.9.3

source:
  git_url: https://gillins@bitbucket.org/landcareresearch/mapaccuracy.git

requirements:
  build:
    - python
    - numpy
    - gdal 2.2.*
    - pyqt 5.6.*
    - tuiview
  run:
    - python
    - numpy
    - gdal 2.2.*
    - pyqt 5.6.*
    - tuiview

build:
  number: 0
  script: python setup.py install

about:
  home: https://bitbucket.org/landcareresearch/mapaccuracy
  license: GPLv2
  summary: Utility for performing map accuracy tests
