package:
  name: mapaccuracy
  version: 0.9.4

source:
  git_url: https://gillins@bitbucket.org/landcareresearch/mapaccuracy.git
  patches:
    # Force no command line install (use entry points)
    # noarch doesn't work with env vars
    - nocmdline.patch

build:
  noarch: python
  number: 3
  script: python setup.py install
  entry_points:
    - mapaccuracy = mapaccuracy.mapaccuracyapplication:runApplication
    - mapaccuracy_txt2shp = mapaccuracy.txt2shp:run

requirements:
  host:
    - python
  run:
    - python
    - tuiview

test:
  imports:
    - mapaccuracy
  commands:
    - mapaccuracy -h

about:
  home: https://bitbucket.org/landcareresearch/mapaccuracy
  license: GPLv2
  summary: Utility for performing map accuracy tests
