package:
  name: gdalaoi
  version: "0.1.0"

source:
  hg_url: https://bitbucket.org/chchrsc/gdalaoi
  hg_tag: tip

build:
  number: 2
  features:
    - vc9 # [win and py27]
    - vc10 # [win and py34]
    - vc14 # [win and py35]
    
requirements:
  build:
    - python  # [win]
    - cmake
    - gdal
    - toolchain
  run:
    - gdal

about:
  home: https://bitbucket.org/chchrsc/gdalaoi
  license: X/MIT
  summary: OGR Driver for Imagine .aoi files
