package:
  name: spdlib
  version: "3.3.0"

build:
    number: 2

source:
  hg_url: https://bitbucket.org/danclewley/spdlib

  patches:
    - cmake_liblaslib.patch

requirements:
  build:
    - cmake
    - python
    - toolchain
    - boost 1.62.*
    - hdf5 1.8.17|1.8.17.*
    - xerces-c
    - gsl
    - gdal 2.1.*
    - geos 3.5.*
    - cgal 4.9.*
    - lastools
  run:
    - python
    - boost 1.62.*
    - hdf5 1.8.17|1.8.17.*
    - xerces-c
    - gsl
    - gdal 2.1.*
    - geos 3.5.*
    - cgal 4.9.*
    - lastools

test:
  commands:
    - spdtranslate -h 
  imports:
    - spdpy
    - spdpy2

build:
    number: 0

about:
  home: http://www.spdlib.org
  license: GPLv3
  summary: The Sorted Pulse Data Library (SPDLib) provides a format for storing and tools for processing discrete return and full waveform LiDAR data from airborne and terrestrial sensors.

