package:
  name: spdlib
  version: "3.3.0"

build:
    number: 4

source:
  hg_url: https://bitbucket.org/petebunting/spdlib

requirements:
  build:
    - python
    - cmake
    - toolchain
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - xerces-c 
    - gsl 2.2.*
    - libgdal 2.1.*
    - geos 3.5.1
    - cgal
    - lastools
  run:
    - python
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - xerces-c
    - gsl 2.2.*
    - libgdal 2.1.*
    - geos 3.5.1
    - cgal
    - lastools

test:
  commands:
    - spdtranslate -h 

about:
  home: http://www.spdlib.org
  license: GPLv3
  summary: The Sorted Pulse Data Library (SPDLib) provides a format for storing and tools for processing discrete return and full waveform LiDAR data from airborne and terrestrial sensors.

