package:
  name: spdlib
  version: "3.3.0"

build:
    number: 5
    # CGAL etc do not support earlier than vc14
    skip: True  # [win and py<35]
    features:
        - vc9  # [win and py27]
        - vc14  # [win and (py35 or py36)]

source:
  hg_url: https://bitbucket.org/petebunting/spdlib

requirements:
  build:
    - python
    # npgpython bindings link to numpy
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - cmake
    - toolchain
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - xerces-c 
    - gsl 2.2.*
    - libgdal 2.1.*
    - geos 3.5.1
    - cgal
    - lastools
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - boost-cpp 1.64.*
    - hdf5 1.8.18|1.8.18.*
    - xerces-c
    - gsl 2.2.*
    - libgdal 2.1.*
    - geos 3.5.1
    - cgal
    - lastools

test:
  commands:
    - spdtranslate -h 

about:
  home: http://www.spdlib.org
  license: GPLv3
  summary: The Sorted Pulse Data Library (SPDLib) provides a format for storing and tools for processing discrete return and full waveform LiDAR data from airborne and terrestrial sensors.

