package:
  name: spdlib
  version: "3.3.0"

build:
    number: 1

source:
  hg_url: https://bitbucket.org/petebunting/spdlib

  patches:
    - cmake_liblaslib.patch

requirements:
  build:
    - cmake
    - toolchain
    - boost 1.61.*
    - hdf5 1.8.17
    - xerces-c 3.1.*
    - gsl 2.1
    - gdal 2.1.*
    - geos 3.4.*
    - cgal 4.8.*
    - lastools
  run:
    - boost 1.61.*
    - hdf5 1.8.17
    - xerces-c 3.1.*
    - gsl 2.1
    - gdal 2.1.*
    - geos 3.4.*
    - cgal 4.8.*
    - lastools

test:
  commands:
    - spdtranslate -h 

build:
    number: 0

about:
  home: http://www.spdlib.org
  license: GPLv3
  summary: The Sorted Pulse Data Library (SPDLib) provides a format for storing and tools for processing discrete return and full waveform LiDAR data from airborne and terrestrial sensors.

