package:
  name: rsgislib
  version: "3.2.0"

build:
    number: 0
    # CGAL etc do not support vc9
    skip: True  # [py27 and win]
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py>=35]
        
source:
  hg_url: https://bitbucket.org/petebunting/rsgislib
  #hg_tag: 3.1.0

requirements:
  build:
    - cmake
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - xerces-c
    - muparser
    - gsl
    - geos 3.5.1
    - gdal 2.2.*
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal
    - python
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]    
    
  run:
    - boost 1.63.*
    - hdf5 1.8.17|1.8.17.*
    - xerces-c
    - muparser
    - gsl
    - geos 3.5.1
    - gdal 2.2.*
    - kealib
    # cgal pulls in appropriate mpir/mpfr/gmp etc for platform
    - cgal
    - python
    - vc   9  # [win and py27]
    - vc  10  # [win and py34]
    - vc  14  # [win and py>=35]
    
about:
  home: http://www.rsgislib.org
  license: GPLv3
  summary: The Remote Sensing and GIS software library (RSGISLib) is a collection of Python modules for processing remote sensing and GIS datasets.

