package:
  name: lastools
  version: "20160606"

source:
  fn: lastools.zip
  url: http://www.cs.unc.edu/~isenburg/lastools/download/lastools.zip
  patches:
    - CMakeLists.patch
    - mydefs.patch  # [win]
    - stdext.patch  # [win and py27]
    - stdext2.patch  # [win and py27]

build:
  number: 0
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - python  # [win]
    - cmake
    - toolchain
    
about:
  home: http://www.cs.unc.edu/~isenburg/lastools/
  license: LGPL2.1
  license_file: LICENSE.txt
  summary: award-winning software for efficient LiDAR processing (with LASzip)
