package:
  name: lastools
  version: "20160124"

source:
  fn: lastools.zip
  url: http://www.cs.unc.edu/~isenburg/lastools/download/lastools.zip
  patches:
    - sharedlib.patch [not win]
    - vc_makefile.patch [win]
    - mydefs.hpp.patch [win]
    - makedef.py.patch [win]

build:
  number: 1
  features:
    - vc9 [win and py27]
    - vc10 [win and py34]
    - vc14 [win and py35]

about:
  home: http://www.cs.unc.edu/~isenburg/lastools/
  license: LGPL
